name: Gitee SYNC2
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee2
      uses: xs314/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:xs314/img"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:xs314/img.git"

    - name: Build Gitee Pages2
      uses: xs314/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: xs314
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: xs314/img
